### PR TITLE
Correction

### PR DESCRIPTION
**Pull request by PonteIneptique**
[Work in progress, do not merge]

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Here you go, I think it should be enough for the repository to be in very very good shape.

**Comment by PonteIneptique** [comment]
Fixes #45 and #42

**Comment by malamatenia** [comment]
Thank you so much! :1st_place_medal: It's about time we learn how to do this by ourselves so we won't bother you every time :)

**Review by malamatenia — APPROVED** [review]
Viewed for Mazarine_Inc59 : 
- pdf to jpg for the source docs
- path to the corresponding image for the.xml docs

And for the repository as a whole :

- restructure and renaming of our folders + explanation in the READMEfile
-installing dependencies for the quality control, correction of the yml and CITATION file.

Went through Noé's corrections but it's better for him to check that everything is in order as well.

Looks amazing Professor Clérice, thank you very very much!

**Review by apogonoe — APPROVED** [review]

**Pull request merged**
